# -*- mode: ruby -*-
# vi: set ft=ruby :

#MIT License
#
#Copyright (c) 2019 dfighter1985
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

# Artifactory binary repository manager install

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # Don't check for Vagrant base box updates automatically
  config.vm.box_check_update = false

  # Forward ports
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
	vb.cpus = 1
    vb.memory = "4096"
  end
  
  # Provision the virtual machine with shell commands
  config.vm.provision "shell", inline: <<-SHELL
	 
	 # Install dependencies
	 apt-get update
	 apt-get install -y default-jre-headless
	 
	 ARTIFACTORY_DEB="jfrog-artifactory-oss-6.12.0.deb"

	 wget https://dl.bintray.com/jfrog/artifactory-debs/pool/main/j/jfrog-artifactory-oss-deb/$ARTIFACTORY_DEB
	 if [ ! -f "$ARTIFACTORY_DEB" ]
	 then
		echo "Failed to download or write Artifactory debian package"
		exit 1
	 fi
	 
	 dpkg -i $ARTIFACTORY_DEB
  SHELL
end
