Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.ssh.username = "debian"
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.provider "openstack" do |os|
    os.identity_api_version = '3'
    os.openstack_auth_url = "https://keystone.REMOVED/v3"
	os.openstack_network_url = "https://apis.c4e.REMOVED/v2.0"
	os.user_domain_name = "Default"
	os.project_domain_name = "default"
	os.username = "OpenStack API username"
	os.password = "OpenStack API password"
	os.project_name = "projectname"
	os.region = "RegionOne";
	os.flavor = "std1.micro"
	os.image = "Debian 10.4"
	os.server_name = "vagrant-test-deploy"
	os.networks = [ 'Flat2' ]
	os.keypair_name = "Key Pair name"
	#The directive below only works with my Vagrant OpenStack patch for SSH IP preference
	#os.ssh_ip_version = 4
  end
  
  config.vm.provision "shell", inline: <<-SHELL
	 export DEBIAN_FRONTEND=noninteractive
	 apt-get update
	 apt-get dist-upgrade -y
	 apt-get install -y mc
  SHELL
end
