# -*- mode: ruby -*-
# vi: set ft=ruby :

#MIT License
#
#Copyright (c) 2019 dfighter1985
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

# One node Kubernetes on Ubuntu Xenial 

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # Don't check for Vagrant base box updates automatically
  config.vm.box_check_update = false

  # Forward ports
  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
	vb.cpus = 2
    vb.memory = "2048"
  end
  
  # Provision the virtual machine with shell commands
  config.vm.provision "shell", inline: <<-SHELL
	 # Set the hostname
	 hostnamectl set-hostname kubernetes-master
	 echo "127.0.0.2	kubernetes-master" >> /etc/hosts
	 
	 # Add Kubernetes Xenial APT repo source
	 curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
	 sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
	 
	 # Install dependencies
	 apt-get update
	 apt-get dist-upgrade -y 
	 apt-get install -y mc jq docker.io kubeadm
	 
	 # Initialize Kubernetes
	 kubeadm init --pod-network-cidr=10.244.10.0/16
	 
	 # These are duplicated because provisioning runs as root, not as the vagrant user
	 mkdir -p /home/vagrant/.kube
	 sudo cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
	 sudo chown $(id -u):$(id -g) /home/vagrant/.kube/config
	 mkdir -p $HOME/.kube
	 sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
	 sudo chown $(id -u):$(id -g) $HOME/.kube/config
	 
	 # Allow pods to run on the master
	 kubectl taint nodes kubernetes-master node-role.kubernetes.io/master:NoSchedule-
	 
	 # Deploy Flannel network
	 kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  SHELL
end
