# -*- mode: ruby -*-
# vi: set ft=ruby :

#MIT License
#
#Copyright (c) 2019 dfighter1985
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

# Jenkins install on Ubuntu Xenial

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # Don't check for Vagrant base box updates automatically
  config.vm.box_check_update = false

  # Forward ports
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 443, host: 443

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
	vb.cpus = 1
    vb.memory = "2048"
  end
  
  # Provision the virtual machine with shell commands
  config.vm.provision "shell", inline: <<-SHELL
	 
	 # Install dependencies
	 wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
	 sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
	 apt-get update
	 apt-get dist-upgrade -y
	 apt-get install -y default-jre-headless docker.io nginx
	 
	 # Enable Docker REST API locally
	 sed -i 's|-H fd://|-H tcp://127.0.0.1:8888 -H fd://|g' /lib/systemd/system/docker.service
	 systemctl daemon-reload
	 service docker restart
	 
	 # Nginx HTTPS terminator
	 mkdir /etc/nginx/ssl
	 openssl req -new -x509 -nodes -subj '/CN=jenkins.local' -out /etc/nginx/ssl/jenkins.crt -keyout /etc/nginx/ssl/jenkins.key -days 3650
	 echo "ssl_certificate /etc/nginx/ssl/jenkins.crt;" > /etc/nginx/snippets/ssl.conf
	 echo "ssl_certificate_key /etc/nginx/ssl/jenkins.key;" >> /etc/nginx/snippets/ssl.conf
	 rm /etc/nginx/sites-enabled/default
	 cp /vagrant/jenkins /etc/nginx/sites-available 
	 ln -s /etc/nginx/sites-available/jenkins /etc/nginx/sites-enabled/jenkins
	 service nginx restart
	 
	 apt-get install -y jenkins
  SHELL
end
